# Site settings
title: Bhargava Varadharajan
description: Personal Website of Bhargava Varadharajan
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Bhargava Varadharajan
user_description: Engineer with keen interest in distributed systems and scale. Outdoorsman. Sport fanatic - CSK, Barcelona, Patriots!
user_title: Software Engineer
email: bhargavavaradh@gmail.com
twitter_username: twbhargav
github_username:  vpbhargav
gplus_username:  google_shut_it_down

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
